server:
  port: 9000
  servlet:
    contextPath: /api

spring:

  application:
    name:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/club-manager?zeroDateTimeBehavior=convertToNull
    username: root

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

